select * from sales_data;

select count(*) from sales_data;

select * from sales_data limit 10;

select sum(sales) from sales_data;

-- What is the total sales and total profit generated by the company?

select sum(sales) as total_sales, sum(profit) as total_profit
from sales_data;

-- Which product generated the highest total sales?

select product,
sum(sales) as highest_sales
from sales_data
group by product
order by highest_sales desc
limit 1;

-- Which region generated the highest profit?

select region, sum(sales) as total_sales from sales_data
group by region
order by total_sales desc
limit 1;


SELECT
    region,
    SUM(profit) AS total_profit
FROM sales_data
GROUP BY region
ORDER BY total_profit DESC
LIMIT 1;

-- List the top 5 customers based on total sales.

select customer, sum(sales) as total_sales
from sales_data
group by customer
order by total_sales desc
limit 5;

-- Find the average profit earned for each product.

select product, round(avg(profit),2) as avg_profit
from sales_data
group by product
order by avg_profit desc;

-- Which month had the highest sales?

select month, sum(sales) as highest_sales
from sales_data
group by month
order by highest_sales desc
limit 1;

-- Find products whose total profit is greater than the average profit of all products.

select product, sum(profit) as total_profit
from sales_data
group by product
Having sum(profit) > (select avg(product_profit) from (select sum(profit) as product_profit from sales_data group by product)t);


-- Find the profit margin (%) for each product.

select product,
round((sum(profit)/sum(sales))*100,2) as profit_margin
from sales_data
group by product
order by profit_margin desc;

-- Find the top 3 most profitable products.

SELECT
    product,
    SUM(profit) AS total_profit
FROM sales_data
GROUP BY product
ORDER BY total_profit DESC
LIMIT 3;

-- Create a sales report showing region-wise performance.

SELECT
    region,
    COUNT(order_id) AS total_orders,
    SUM(sales) AS total_sales,
    SUM(profit) AS total_profit,
    ROUND(AVG(sales),2) AS avg_sales
FROM sales_data
GROUP BY region
ORDER BY total_sales DESC;

-- Rank products based on total sales.

SELECT
    product,
    SUM(sales) AS total_sales,
    RANK() OVER(ORDER BY SUM(sales) DESC) AS sales_rank
FROM sales_data
GROUP BY product;